CREATE DATABASE touresbalon;

USE touresbalon;

CREATE TABLE SALES_ORDER(
	ID INT AUTO_INCREMENT,
	ORDER_DATE DATE NOT NULL,
	PRICE NUMERIC(18) NOT NULL,
	STATUS VARCHAR(4) NOT NULL,
	COMMENTS VARCHAR(4000),
	CUSTOMER_ID VARCHAR(50) NOT NULL,
	CONSTRAINT sales_order_pk PRIMARY KEY (ID)
);

create table ORDER_ITEM(	
	ID INTEGER AUTO_INCREMENT,
	PRODUCT_ID NUMERIC(18) NOT NULL,
	PRODUCT_NAME VARCHAR(250),
	PRICE NUMERIC(18) NOT NULL,
	QUANTITY NUMERIC(4) NOT NULL,
	ORDER_ID INT NOT NULL,
	CONSTRAINT order_item_pk PRIMARY KEY (ID),
	CONSTRAINT fk_sales FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ID)
);


insert into SALES_ORDER (ORDER_DATE,PRICE,STATUS,COMMENTS,CUSTOMER_ID) values(CURDATE(),142536, 'HOLD', 'ESTAS SON LAS OBSERVACIONES DE ESTA ORDEN','rfranco' );

insert into ORDER_ITEM (PRODUCT_ID,PRODUCT_NAME,PRICE,QUANTITY,ORDER_ID)values(123456789,'XXXX',4124571,5,1);
insert into ORDER_ITEM (PRODUCT_ID,PRODUCT_NAME,PRICE,QUANTITY,ORDER_ID)values(12471,'YYYY',25147,10,1);
insert into ORDER_ITEM (PRODUCT_ID,PRODUCT_NAME,PRICE,QUANTITY,ORDER_ID)values(74122896,'ZZZZZ',789456123,5,1);
